# Generated by Django 6.0 on 2026-02-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Order_Placed', 'Order Placed'), ('Confirmed', 'Confirmed'), ('Shipped', 'Shipped'), ('Out_for_Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Order_Placed', max_length=30),
        ),
    ]
