# Generated by Django 4.2.7 on 2026-02-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=100, unique=True)),
                ('manufacturing_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Batches',
                'ordering': ['manufacturing_date', 'created_at'],
            },
        ),
    ]
