# Generated by Django 4.2.7 on 2026-02-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_productimage_options_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('pack', 'Pack'), ('box', 'Box')], default='kg', help_text='Unit type for stock display (e.g., kg, piece, liter)', max_length=10),
        ),
    ]
