# Generated by Django 6.0 on 2026-02-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_order_date_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
    ]
