# Generated by Django 4.2.7 on 2026-02-23 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_offer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
    ]
