# Generated by Django 4.2.7 on 2026-02-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Grocery Admin', max_length=200)),
                ('store_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('contact_email', models.EmailField(default='admin@example.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 00000 00000', max_length=20)),
                ('store_address', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('delivery_charge_type', models.CharField(default='fixed', max_length=20)),
                ('delivery_charge', models.DecimalField(decimal_places=2, default=40, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=199, max_digits=10)),
                ('free_delivery_limit', models.DecimalField(decimal_places=2, default=999, max_digits=10)),
                ('delivery_slots', models.TextField(blank=True, null=True)),
                ('service_pincodes', models.TextField(blank=True, null=True)),
                ('cod_enabled', models.BooleanField(default=True)),
                ('online_payments_enabled', models.BooleanField(default=True)),
                ('pg_api_key', models.CharField(blank=True, max_length=200, null=True)),
                ('pg_secret_key', models.CharField(blank=True, max_length=200, null=True)),
                ('refund_mode', models.CharField(default='manual', max_length=20)),
                ('default_tax', models.DecimalField(decimal_places=2, default=18, max_digits=5)),
                ('low_stock_limit', models.IntegerField(default=10)),
                ('email_notif', models.BooleanField(default=True)),
                ('sms_notif', models.BooleanField(default=False)),
                ('push_notif', models.BooleanField(default=False)),
                ('whatsapp_api', models.CharField(blank=True, max_length=200, null=True)),
                ('auto_confirm_orders', models.BooleanField(default=True)),
                ('order_workflow', models.TextField(blank=True, null=True)),
                ('cancel_policy', models.TextField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('analytics_id', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
