# Generated by Django 4.2.7 on 2026-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='box', help_text='Emoji icon for category', max_length=10, blank=True),
        ),
    ]
